version: '3.8'
services:
    db:
        image: postgres:13.1
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_DB=bookingcare
            - POSTGRES_PASSWORD=123123
        ports:
            - '5433:5432'
        expose:
            - 5432

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        environment:
            - DB_PORT=5432
            - DB_HOST=db
            - URL_REACT=http://localhost
            # - DB_HOST=host.docker.internal
        ports:
            - 8080:8080
        expose:
            - 8080

    nginx:
        image: nginx:1.23.3
        ports:
            - 80:80
        volumes:
            - ../bookingcare-reactjs/build:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
# docker compose -p doctorcare-sern up -d
